Develop
julialukshina/java-explore-with-me pull request #1
Opened 2022-10-04 10:12 UTC by julialukshina

Для получения отчета по тестам

2022-10-07 21:49 UTC, sergeymamonov requested changes
Добрый день. Работа выполнена хорошо. Отлично, что Readme содержит много подробной информации о проекте.
Обратите внимание на наименование коммитов. Оно должно быть информативным не только для вас, но и для всех остальных. Maven враппер нужно перенести в корень. Зачем гитигнор в каждом модуле? Достаточно одного в корне проекта. У pom файлов модулей должен быть родительский pom файл из корня, а не спрингбутовый. Лучше, чтобы были тесты на свой код. Но если не собираетесь писать тесты, то лучше папки с тестами удалить. Нигде не должно быть закомментированного кода. При создании таблиц необхдимо ограничивать размер varchar. Чаще всего названия таблиц, ограничений и так далее в скриптах пишут строчными буквами. Пустой конструктор не обязательно писать самостоятельно. Можно воспользоваться аннотацией Lombok. Импорт через * не всегда хорошо. Можно получить сложные в нахождении ошибки. Лучше всегда явно импортировать то, что нужно. Сейчас логи пишутся где-то на русском, где-то на английском. Лучше писать логи на одном языке. Английский предпочтительнее, но не настаиваю на выборе языка. Лучше не использовать My в названии классов. Все-таки это выпускной проект, приближенный к реальному приложению. Проверьте, в некоторых классах пропущены модификаторы доступа для полей. В накоторых классах написаны sql операторы сточными буквами, в некоторых классах - заглавными. Лучше делать единообразно.

2022-10-07 21:49 UTC, sergeymamonov commented on docker-compose.yaml
> +#      - SERVER_URL=http://statistics:9090
Не должно быть закомментированного кода.

2022-10-07 21:49 UTC, sergeymamonov commented on service/pom.xml
> +        <!--        <dependency>-->
Не должно быть закомментированного кода.

2022-10-07 21:49 UTC, sergeymamonov commented on service/src/main/resources/schema.sql
> +--     events_id bigint[] NOT NULL,
Не должно быть закомментированного кода.

2022-10-07 21:49 UTC, sergeymamonov commented on service/src/main/resources/schema.sql
> +    CONSTRAINT pk_Categories PRIMARY KEY (id)
чаще всего названия пишут строчными буквами.

2022-10-07 21:49 UTC, sergeymamonov commented on service/src/main/java/ru/yandex/practicum/service/dto/categories/NewCategoryDto.java
> +    public NewCategoryDto() {
Действительно нужно писать руками пустой конструктор здесь? Заменить с помощью аннотации Lombok можно?

2022-10-07 21:49 UTC, sergeymamonov commented on service/src/main/java/ru/yandex/practicum/service/dto/statistics/EndpointHit.java
> +    String uri;
Пропущен модификатор доступа для этого поля и полей ниже.

2022-10-07 21:49 UTC, sergeymamonov commented on service/src/main/java/ru/yandex/practicum/service/dto/statistics/ViewStats.java
> +    String uri;
Пропущен модификатор доступа для полей класса.

2022-10-07 21:49 UTC, sergeymamonov commented on service/src/main/java/ru/yandex/practicum/service/enums/Sort.java
> +    EVENT_DATE, VIEWS, UNSUPPORTED_SORT
Обычно каждое перечисление пишут с новой строки.

2022-10-07 21:49 UTC, sergeymamonov commented on service/src/main/java/ru/yandex/practicum/service/exeptions/MyValidationException.java
> +public class MyValidationException extends RuntimeException {
Проект хоть и учебный, но не настолько, чтобы использовать My... в названиях. ValidationException - будет достаточно.

2022-10-07 21:49 UTC, sergeymamonov commented on service/src/main/java/ru/yandex/practicum/service/errors/ControllerAdvice.java
> +public class ControllerAdvice extends ResponseEntityExceptionHandler {
Обычно такой класс называют именем содержащим ExceptionHandler.

2022-10-07 21:49 UTC, sergeymamonov commented on service/src/main/java/ru/yandex/practicum/service/errors/ControllerAdvice.java
> +    public ResponseEntity<Object> handleConstraintViolationException(ConstraintViolationException e, WebRequest request) {
А если в рантайме возникнет ошибка, отличная от этих двух, которые принимает метод? Тогда обработчик не обработает такую ошибку.

2022-10-07 21:49 UTC, sergeymamonov commented on service/src/main/java/ru/yandex/practicum/service/repositories/EventStorage.java
> +    private DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
Поле нигде не используется.

2022-10-07 21:49 UTC, sergeymamonov commented on service/src/main/java/ru/yandex/practicum/service/repositories/EventStorage.java
> +        Event event = new Event(id,
Можно сразу возвращать евент, без создания промежуточной переменной

2022-10-07 21:49 UTC, sergeymamonov commented on service/src/main/java/ru/yandex/practicum/service/services/events/EventAdminServiceImpl.java
> +                e.getMessage();
Какой результат выполнения этой строки? Если было желание куда-нибудь вывести стектрейс, то это не сделано.

2022-10-07 21:49 UTC, sergeymamonov commented on service/src/main/java/ru/yandex/practicum/service/services/events/EventAdminServiceImpl.java
> +        if (start != null || (start == null && end == null)) {
Если start != null, то попадаем во вторую часть блока ИЛИ, тогда уже лишнее проверять, что start == null

2022-10-07 21:49 UTC, sergeymamonov commented on service/src/main/java/ru/yandex/practicum/service/services/events/EventPublicServiceImpl.java
> +            if (sort.equals(Sort.EVENT_DATE) || sort == null) {
Если sort будет равен null, то код не дойдет до проверки sort == null, а уже раньше на sort.equals() будет NPE.

2022-10-07 21:49 UTC, sergeymamonov commented on service/src/main/java/ru/yandex/practicum/service/MyPageable.java
> +public class MyPageable implements Pageable {
Лучше переименуйте, чтобы название не содержало My

2022-10-07 21:49 UTC, sergeymamonov commented on service/src/main/java/ru/yandex/practicum/service/MyPageable.java
> +    private static final int DEFAULT_PAGE_SIZE = 10;
Константа где-то используется?

2022-10-07 21:49 UTC, sergeymamonov commented on statistics/src/main/java/ru/yandex/practicum/statistics/dto/EndpointHit.java
> +    String uri;
Потеряны модификаторы доступа.

2022-10-07 21:49 UTC, sergeymamonov commented on statistics/src/main/java/ru/yandex/practicum/statistics/dto/ViewStats.java
> +    String uri;
Модификаторы.

2022-10-07 21:49 UTC, sergeymamonov commented on statistics/src/main/java/ru/yandex/practicum/statistics/services/StatisticsServiceImpl.java
> +            throw new RuntimeException(ex.getCause());
Мы ловим UnsupportedEncodingException и кидаем общую ошибку. Зачем так сделано? Если мы знаем, что может возникнуть обрабатываемо исключение, то мы можем обработать его или прокинуть выше. Но кидать необрабатываемое исключение - не самая лучшая практика.

2022-10-08 12:04 UTC, julialukshina commented on docker-compose.yaml
> +#      - SERVER_URL=http://statistics:9090
Исправлено

2022-10-08 12:04 UTC, julialukshina commented on service/pom.xml
> +        <!--        <dependency>-->
Исправлено

2022-10-08 12:04 UTC, julialukshina commented on service/src/main/resources/schema.sql
> +--     events_id bigint[] NOT NULL,
Исправлено

2022-10-08 12:04 UTC, julialukshina commented on service/src/main/resources/schema.sql
> +    CONSTRAINT pk_Categories PRIMARY KEY (id)
Исправлено

2022-10-08 12:08 UTC, julialukshina commented on service/src/main/java/ru/yandex/practicum/service/dto/categories/NewCategoryDto.java
> +    public NewCategoryDto() {
Исправлено

2022-10-08 12:10 UTC, julialukshina commented on service/src/main/java/ru/yandex/practicum/service/MyPageable.java
> +public class MyPageable implements Pageable {
Исправлено

2022-10-08 12:10 UTC, julialukshina commented on service/src/main/java/ru/yandex/practicum/service/MyPageable.java
> +    private static final int DEFAULT_PAGE_SIZE = 10;
Убрала

2022-10-08 12:13 UTC, julialukshina commented on statistics/src/main/java/ru/yandex/practicum/statistics/dto/EndpointHit.java
> +    String uri;
Исправлено

2022-10-08 12:13 UTC, julialukshina commented on statistics/src/main/java/ru/yandex/practicum/statistics/dto/ViewStats.java
> +    String uri;
Исправлено

2022-10-08 12:14 UTC, julialukshina commented on service/src/main/java/ru/yandex/practicum/service/dto/statistics/EndpointHit.java
> +    String uri;
Исправлено

2022-10-08 12:14 UTC, julialukshina commented on service/src/main/java/ru/yandex/practicum/service/dto/statistics/ViewStats.java
> +    String uri;
Исправлено

2022-10-08 12:15 UTC, julialukshina commented on service/src/main/java/ru/yandex/practicum/service/enums/Sort.java
> +    EVENT_DATE, VIEWS, UNSUPPORTED_SORT
Исправлено

2022-10-08 12:15 UTC, julialukshina commented on service/src/main/java/ru/yandex/practicum/service/exeptions/MyValidationException.java
> +public class MyValidationException extends RuntimeException {
Исправлено

2022-10-08 12:16 UTC, julialukshina commented on service/src/main/java/ru/yandex/practicum/service/errors/ControllerAdvice.java
> +public class ControllerAdvice extends ResponseEntityExceptionHandler {
Исправлено

2022-10-08 12:17 UTC, julialukshina commented on service/src/main/java/ru/yandex/practicum/service/repositories/EventStorage.java
> +    private DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
Исправлено

2022-10-08 12:18 UTC, julialukshina commented on service/src/main/java/ru/yandex/practicum/service/repositories/EventStorage.java
> +        Event event = new Event(id,
Исправлено

2022-10-08 12:25 UTC, julialukshina commented on service/src/main/java/ru/yandex/practicum/service/services/events/EventAdminServiceImpl.java
> +                e.getMessage();
Исправлено

2022-10-08 12:28 UTC, julialukshina commented on service/src/main/java/ru/yandex/practicum/service/services/events/EventAdminServiceImpl.java
> +        if (start != null || (start == null && end == null)) {
Исправлено

2022-10-08 12:55 UTC, julialukshina commented on service/src/main/java/ru/yandex/practicum/service/services/events/EventPublicServiceImpl.java
> +            if (sort.equals(Sort.EVENT_DATE) || sort == null) {
Исправлено

2022-10-08 13:04 UTC, julialukshina commented on statistics/src/main/java/ru/yandex/practicum/statistics/services/StatisticsServiceImpl.java
> +            throw new RuntimeException(ex.getCause());
Исправлено

2022-10-09 19:46 UTC, sergeymamonov approved these changes

2022-10-09 19:46 UTC, sergeymamonov commented on service/src/main/java/ru/yandex/practicum/service/repositories/UserRepository.java
> +    @Query("select u from User u where u.id in :ids")
Здесь операторы остались строчными буквами.

2022-10-09 19:46 UTC, sergeymamonov commented on service/src/main/java/ru/yandex/practicum/service/services/events/EventAdminServiceImpl.java
> +                //               e.getStackTrace();
Закомментированный код.

2022-10-11 16:21 UTC, merged